typography_spectrum: 0.9277220778167248
color:
  brandColors:
    - '#7D8A2E'
    - '#C9D787'
    - '#FFFFFF'
    - '#FFC0A9'
    - '#FF8598'
  brandStrength: 0.12090660282410681
  lightness: 0.7971692853607237
  saturation: 0.9167037911247462
  rhythmicContrast: 0.36124134506098926
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6415376584045589
analytics:
  google: null
  facebook: null
  twitter: null
name: Author Interviews
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: ' gratitude'
    id: 8f0d0223-ada4-44b9-bad4-2573e07a6214
    type: content
  - name: fear of success
    id: 060e328b-ccea-4966-a465-f3f37db1a8ba
    type: content
  - name: benifits of being in the moment
    id: fc89243d-52d2-4f0f-9929-c4f1496c4f10
    type: content
  - name: live and be happy
    id: a10177fa-68fa-4ddd-9834-90f9c866c107
    type: content
  - name: safest place in the world
    id: c07c3d69-4e6d-487d-9da6-437828c58a0e
    type: content
  - name: Links - Press Releases
    id: 73690951-a101-46b9-91c3-11ee92f0c5bb
    type: content
favicon: null
purpose: []
