typography_spectrum: 0.14014753978699446
color:
  brandColors:
    - '#2F2933'
    - '#01A2A6'
    - '#29D9C2'
    - '#BDF271'
    - '#FFFFA6'
  brandStrength: 0.7607454415410757
  lightness: 0.2201887818519026
  saturation: 0.13269567233510315
  rhythmicContrast: 0.4690254721790552
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.34786989144049585
analytics:
  google: null
  facebook: null
  twitter: null
name: Author Interviews
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: a short author interview
    id: 68708f11-8173-4336-b39d-e6f9c50510b6
    type: content
  - name: Balboa Press Interview
    id: c674d3b7-3159-4bcf-9b86-957ccc2b60c6
    type: content
favicon: null
purpose: []
