name: Author Interviews
favicon: null
layout_spectrum: 0.940779521362856
typography_spectrum: 0.16605760110542178
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.07077403389848769
  lightness: 0.03355301055125892
  saturation: 0.7243802996817976
  rhythmicContrast: 0.31440362171269953
purpose: []
