typography_spectrum: 0.14014753978699446
color:
  brandColors:
    - '#2F2933'
    - '#01A2A6'
    - '#29D9C2'
    - '#BDF271'
    - '#FFFFA6'
  brandStrength: 0.7607454415410757
  lightness: 0.2201887818519026
  saturation: 0.13269567233510315
  rhythmicContrast: 0.4690254721790552
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.34786989144049585
analytics:
  google: null
  facebook: null
  twitter: null
name: Author Interviews
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: a short author interview
    id: 68708f11-8173-4336-b39d-e6f9c50510b6
    type: content
  - name: Rich Okun
    id: c674d3b7-3159-4bcf-9b86-957ccc2b60c6
    type: content
  - name: 'Author Interview: Rich Okun'
    id: 466f169e-134b-4f3d-9e1e-50b8e203e9ed
    type: content
  - name: 'Life in vignettes: Rich Okun'
    id: 6114158f-cab6-46e1-b0a5-2c8d3d344bb6
    type: content
  - name: 'Book Lovers Corner The Sun, the Moon, the Stars, and Maya'
    id: e156f04d-834c-4906-9f31-bd1137a1b1ea
    type: content
  - name: That's The Spirit 7 28 13 Author Rich Okun
    id: 2c6804be-afce-461d-8233-3e68c20f6714
    type: content
favicon: null
purpose: []
