layout_spectrum: 0.34786989144049585
typography_spectrum: 0.14014753978699446
color:
  brandColors:
    - '#2F2933'
    - '#01A2A6'
    - '#29D9C2'
    - '#BDF271'
    - '#FFFFA6'
  brandStrength: 0.7607454415410757
  lightness: 0.2201887818519026
  saturation: 0.13269567233510315
  rhythmicContrast: 0.4690254721790552
name: Author Interviews
favicon: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
