typography_spectrum: 0.14014753978699446
color:
  brandColors:
    - '#2F2933'
    - '#01A2A6'
    - '#29D9C2'
    - '#BDF271'
    - '#FFFFA6'
  brandStrength: 0.7607454415410757
  lightness: 0.2201887818519026
  saturation: 0.13269567233510315
  rhythmicContrast: 0.4690254721790552
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.34786989144049585
analytics:
  google: null
  facebook: null
  twitter: null
name: Author Interviews
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: 'Book Lovers Corner The Sun, the Moon, the Stars, and Maya'
    id: e156f04d-834c-4906-9f31-bd1137a1b1ea
    type: content
  - name: That's The Spirit 7 28 13 Author Rich Okun
    id: 2c6804be-afce-461d-8233-3e68c20f6714
    type: content
  - name: Links
    id: 73690951-a101-46b9-91c3-11ee92f0c5bb
    type: content
favicon: null
purpose: []
