typography_spectrum: 0.19396896404214203
color:
  brandColors:
    - '#7D8A2E'
    - '#C9D787'
    - '#FFFFFF'
    - '#FFC0A9'
    - '#FF8598'
  brandStrength: 0.12090660282410681
  lightness: 0.7971692853607237
  saturation: 0.9167037911247462
  rhythmicContrast: 0.36124134506098926
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.4428756854031235
analytics:
  google: null
  facebook: null
  twitter: null
name: Author Interviews
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: a short author interview
    id: 68708f11-8173-4336-b39d-e6f9c50510b6
    type: content
  - name: Balboa Press Interview
    id: c674d3b7-3159-4bcf-9b86-957ccc2b60c6
    type: content
  - name: 'Author Interview: Rich Okun'
    id: 466f169e-134b-4f3d-9e1e-50b8e203e9ed
    type: content
  - name: 'Book Lovers Corner The Sun, the Moon, the Stars, and Maya'
    id: e156f04d-834c-4906-9f31-bd1137a1b1ea
    type: content
  - name: That's The Spirit 7 28 13 Author Rich Okun
    id: 2c6804be-afce-461d-8233-3e68c20f6714
    type: content
  - name: Links
    id: 73690951-a101-46b9-91c3-11ee92f0c5bb
    type: content
  - name: Ivy Moon Press
    url: 'https://ivymoonpress.wordpress.com/2013/11/'
    type: external
  - name: rich okun benifits of being in the moment
    id: fc89243d-52d2-4f0f-9929-c4f1496c4f10
    type: content
  - name: rich okun fear of success
    id: 060e328b-ccea-4966-a465-f3f37db1a8ba
    type: content
favicon: null
purpose: []
