name: Author Interviews
favicon: null
layout_spectrum: 0.36354
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9c5e2f'
    - '#160b09'
    - '#e7e7e7'
    - '#cf968f'
    - '#898480'
  brandStrength: 0.1875
  lightness: 0.5625
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
